CREATE DATABASE IF NOT EXISTS face_db;

USE face_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    vector_wajah LONGTEXT NOT NULL
);
